// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v5.29.0
// source: aeropuertos.proto

package aeropuertos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Solicitud para obtener aeropuertos
type GetAereopuertosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre      string `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	CodigoIata  string `protobuf:"bytes,3,opt,name=codigo_iata,json=codigoIata,proto3" json:"codigo_iata,omitempty"`
	Ubicacion   string `protobuf:"bytes,4,opt,name=ubicacion,proto3" json:"ubicacion,omitempty"`
	Latitud     string `protobuf:"bytes,5,opt,name=latitud,proto3" json:"latitud,omitempty"`
	Longitud    string `protobuf:"bytes,6,opt,name=longitud,proto3" json:"longitud,omitempty"`
	ZonaHoraria string `protobuf:"bytes,7,opt,name=zona_horaria,json=zonaHoraria,proto3" json:"zona_horaria,omitempty"`
	Url         string `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetAereopuertosRequest) Reset() {
	*x = GetAereopuertosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aeropuertos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAereopuertosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAereopuertosRequest) ProtoMessage() {}

func (x *GetAereopuertosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aeropuertos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAereopuertosRequest.ProtoReflect.Descriptor instead.
func (*GetAereopuertosRequest) Descriptor() ([]byte, []int) {
	return file_aeropuertos_proto_rawDescGZIP(), []int{0}
}

func (x *GetAereopuertosRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetAereopuertosRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *GetAereopuertosRequest) GetCodigoIata() string {
	if x != nil {
		return x.CodigoIata
	}
	return ""
}

func (x *GetAereopuertosRequest) GetUbicacion() string {
	if x != nil {
		return x.Ubicacion
	}
	return ""
}

func (x *GetAereopuertosRequest) GetLatitud() string {
	if x != nil {
		return x.Latitud
	}
	return ""
}

func (x *GetAereopuertosRequest) GetLongitud() string {
	if x != nil {
		return x.Longitud
	}
	return ""
}

func (x *GetAereopuertosRequest) GetZonaHoraria() string {
	if x != nil {
		return x.ZonaHoraria
	}
	return ""
}

func (x *GetAereopuertosRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Respuesta con una lista de aeropuertos
type GetAereopuertosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Aereopuertos []*Aereopuerto `protobuf:"bytes,1,rep,name=aereopuertos,proto3" json:"aereopuertos,omitempty"` // Aquí utilizas el mensaje Aereopuerto
}

func (x *GetAereopuertosResponse) Reset() {
	*x = GetAereopuertosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aeropuertos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAereopuertosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAereopuertosResponse) ProtoMessage() {}

func (x *GetAereopuertosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aeropuertos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAereopuertosResponse.ProtoReflect.Descriptor instead.
func (*GetAereopuertosResponse) Descriptor() ([]byte, []int) {
	return file_aeropuertos_proto_rawDescGZIP(), []int{1}
}

func (x *GetAereopuertosResponse) GetAereopuertos() []*Aereopuerto {
	if x != nil {
		return x.Aereopuertos
	}
	return nil
}

// Definición de Aereopuerto
type Aereopuerto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre      string  `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	CodigoIata  string  `protobuf:"bytes,2,opt,name=codigo_iata,json=codigoIata,proto3" json:"codigo_iata,omitempty"`
	Ubicacion   string  `protobuf:"bytes,3,opt,name=ubicacion,proto3" json:"ubicacion,omitempty"`
	Latitud     float64 `protobuf:"fixed64,4,opt,name=latitud,proto3" json:"latitud,omitempty"`
	Longitud    float64 `protobuf:"fixed64,5,opt,name=longitud,proto3" json:"longitud,omitempty"`
	ZonaHoraria string  `protobuf:"bytes,6,opt,name=zona_horaria,json=zonaHoraria,proto3" json:"zona_horaria,omitempty"`
	Url         string  `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Aereopuerto) Reset() {
	*x = Aereopuerto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aeropuertos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Aereopuerto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aereopuerto) ProtoMessage() {}

func (x *Aereopuerto) ProtoReflect() protoreflect.Message {
	mi := &file_aeropuertos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aereopuerto.ProtoReflect.Descriptor instead.
func (*Aereopuerto) Descriptor() ([]byte, []int) {
	return file_aeropuertos_proto_rawDescGZIP(), []int{2}
}

func (x *Aereopuerto) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Aereopuerto) GetCodigoIata() string {
	if x != nil {
		return x.CodigoIata
	}
	return ""
}

func (x *Aereopuerto) GetUbicacion() string {
	if x != nil {
		return x.Ubicacion
	}
	return ""
}

func (x *Aereopuerto) GetLatitud() float64 {
	if x != nil {
		return x.Latitud
	}
	return 0
}

func (x *Aereopuerto) GetLongitud() float64 {
	if x != nil {
		return x.Longitud
	}
	return 0
}

func (x *Aereopuerto) GetZonaHoraria() string {
	if x != nil {
		return x.ZonaHoraria
	}
	return ""
}

func (x *Aereopuerto) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_aeropuertos_proto protoreflect.FileDescriptor

var file_aeropuertos_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x65, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x65, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x22,
	0xea, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x65, 0x72, 0x65, 0x6f, 0x70, 0x75, 0x65, 0x72,
	0x74, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f,
	0x6d, 0x62, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62,
	0x72, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x5f, 0x69, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x49,
	0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x62, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x62, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c,
	0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x7a, 0x6f, 0x6e, 0x61, 0x5f,
	0x68, 0x6f, 0x72, 0x61, 0x72, 0x69, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x7a,
	0x6f, 0x6e, 0x61, 0x48, 0x6f, 0x72, 0x61, 0x72, 0x69, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x56, 0x0a, 0x17,
	0x47, 0x65, 0x74, 0x41, 0x65, 0x72, 0x65, 0x6f, 0x70, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x61, 0x65, 0x72, 0x65, 0x6f,
	0x70, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x61, 0x65, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x2e, 0x41, 0x65, 0x72, 0x65, 0x6f,
	0x70, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x52, 0x0c, 0x61, 0x65, 0x72, 0x65, 0x6f, 0x70, 0x75, 0x65,
	0x72, 0x74, 0x6f, 0x73, 0x22, 0xcf, 0x01, 0x0a, 0x0b, 0x41, 0x65, 0x72, 0x65, 0x6f, 0x70, 0x75,
	0x65, 0x72, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x5f, 0x69, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x49, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a,
	0x09, 0x75, 0x62, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x75, 0x62, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6c,
	0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x6c, 0x61,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x7a, 0x6f, 0x6e, 0x61, 0x5f, 0x68, 0x6f, 0x72, 0x61, 0x72, 0x69,
	0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x7a, 0x6f, 0x6e, 0x61, 0x48, 0x6f, 0x72,
	0x61, 0x72, 0x69, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x32, 0x6c, 0x0a, 0x13, 0x41, 0x65, 0x72, 0x65, 0x6f, 0x70,
	0x75, 0x65, 0x72, 0x74, 0x6f, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a,
	0x08, 0x47, 0x65, 0x74, 0x52, 0x75, 0x74, 0x61, 0x73, 0x12, 0x22, 0x2e, 0x61, 0x65, 0x72, 0x6f,
	0x70, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x65, 0x72, 0x65, 0x6f, 0x70,
	0x75, 0x65, 0x72, 0x74, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x61, 0x65, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x65,
	0x72, 0x65, 0x6f, 0x70, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x61, 0x65, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_aeropuertos_proto_rawDescOnce sync.Once
	file_aeropuertos_proto_rawDescData = file_aeropuertos_proto_rawDesc
)

func file_aeropuertos_proto_rawDescGZIP() []byte {
	file_aeropuertos_proto_rawDescOnce.Do(func() {
		file_aeropuertos_proto_rawDescData = protoimpl.X.CompressGZIP(file_aeropuertos_proto_rawDescData)
	})
	return file_aeropuertos_proto_rawDescData
}

var file_aeropuertos_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_aeropuertos_proto_goTypes = []interface{}{
	(*GetAereopuertosRequest)(nil),  // 0: aeropuerto.GetAereopuertosRequest
	(*GetAereopuertosResponse)(nil), // 1: aeropuerto.GetAereopuertosResponse
	(*Aereopuerto)(nil),             // 2: aeropuerto.Aereopuerto
}
var file_aeropuertos_proto_depIdxs = []int32{
	2, // 0: aeropuerto.GetAereopuertosResponse.aereopuertos:type_name -> aeropuerto.Aereopuerto
	0, // 1: aeropuerto.AereopuertosService.GetRutas:input_type -> aeropuerto.GetAereopuertosRequest
	1, // 2: aeropuerto.AereopuertosService.GetRutas:output_type -> aeropuerto.GetAereopuertosResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_aeropuertos_proto_init() }
func file_aeropuertos_proto_init() {
	if File_aeropuertos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aeropuertos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAereopuertosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aeropuertos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAereopuertosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aeropuertos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Aereopuerto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aeropuertos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aeropuertos_proto_goTypes,
		DependencyIndexes: file_aeropuertos_proto_depIdxs,
		MessageInfos:      file_aeropuertos_proto_msgTypes,
	}.Build()
	File_aeropuertos_proto = out.File
	file_aeropuertos_proto_rawDesc = nil
	file_aeropuertos_proto_goTypes = nil
	file_aeropuertos_proto_depIdxs = nil
}
